name: CI Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install OpenMPI
        run: sudo apt-get install openmpi-bin libopenmpi-dev
      - name: Build w/o HDF5 w/ Metall
        run: |
          mkdir build && cd build
          cmake ../ -DSALTATLAS_USE_HDF5=OFF -DSALTATLAS_USE_METALL=ON
          make -j